
services:
  gradio_sql_app:
    image: jpcosteira/formsipg
    container_name: bika
    ports:
      - "7860:7860"
    volumes:
      - ./app:/home/jpc/
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped
