
services:
  gradio_sql_app:
    build: .
    container_name: bika
    ports:
      - "7862:7860"
      - "8882:8888"
    volumes:
      - ./app:/home/jpc/app
      - ./data:/home/jpc/app/data
      - ./databikabase:/home/jpc/databikabase
      - ./home:/home/jpc/
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped
