database:
  name: "data/user_data.db"
  table: "users"
interface:
  tabs:
    - name: "Hx Clinica"
      fields:
        - name: "DataInscr"
          label: "Data de Inscrição"
          type: "text"
        - name: "motivo"
          label: "Motivo para referenciação"
          type: "text"
        - name: "txinicial"
          label: "Tx inicial Noutra instituição"
          type: "text"
    - name: "Imagem - Estadiamento"
      fields:
        - name: "nnn"
          label: "Subscribe to Newsletter"
          type: "checkbox"
        - name: "emailbx"
          label: "Emailbx"
          type: "text"
          default: true
    - name: "Mais um Tab"
      fields:
        - name: "newasletter"
          label: "Subscribe to Newsletter"
          type: "checkbox"
        - name: "emaialbx"
          label: "Emaialbx"
          type: "text"
          default: true
