database:
  name: migration.db
  table: registo

auth:
  password: "sipg2dsi"

interface:
  tabs:
    - name: "Dados ISR/Omni"
      layout:
        - row: true
          fields:
            - name: "name"
              type: "text"
              label: "Name"
            - name: "username_omni"
              type: "text"
              label: "Username@omni"
    - name: "Dados DSI/Sigma"
      layout:
        - row: true
          fields:
            - name: "username_dsi"
              label: "Username@DSI (istxxxxx)"
              type: "text"
